nome = input("Digite seu nome: ")
idade = int(input("Digite sua idade: "))
print(f"Seu nome é {nome} e você tem {idade} anos.")
print()
print("----------------------------------------------")
nome2 = input("Digite seu nome: ")
idade2 = int(input("Digite sua idade: "))
print(f"Seu nome é {nome2} e você tem {idade2} anos.")
print()
print("----------------------------------------------")